name: CI

on:
  push:
    branches: [develop, main]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}-group
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'          
          distribution: 'temurin'
          cache: 'maven'

      - name: Build & run unit tests
        run: mvn -B -ntp verify

      - name: Upload surefire reports on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: |
            **/target/surefire-reports/**
            **/target/failsafe-reports/**

      - name: Save Jar file
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*-SNAPSHOT.jar
          retention-days: 1

